### ISSUE TITLE
Support update wiki from Rmarkdown

### ISSUE THREAD

**Issue by harryprince** [line/conflr#11] opened 2019-02-18 08:59 UTC
currently, I can not update an existing Wiki by `conflr` directly.

I wish to use conflr in Rscript and directly update the content with function.

it looks like this:

```
conflr::confl_login(username = "xxx",passwd = "xxx",url = "xxx.com")
conflr::confl_update_post_from_Rmd("test.Rmd",space = "xxx",page_id = 123456)
```

**Comment by yutannihilation** [comment] 2019-02-18 09:05
You can update existing pages by Rmds with the same title. Could you try?

> I wish to use conflr in Rscript and directly update the content with function.

This is what I will address in #10. Sorry for inconvenience for now...

**Comment by harryprince** [comment] 2019-02-18 09:15
I know `conflr::confl_create_post_from_Rmd("test.Rmd")` can do the same thing with copy-paste pageid in a Web UI, however, it is a hinder of automation.

**Comment by harryprince** [comment] 2019-02-18 09:17
maybe upload html is another option, the html file is generated by .Rmd.

**Comment by yutannihilation** [comment] 2019-02-18 09:36
Thanks for clarification! Then, I'm closing this as a duplicate of #10. If you have more ideas, please comment there.

**Closed by yutannihilation** 2019-02-18 09:36 UTC
